language: bash
dist: bionic
before_script:
    - apt install ruby-coveralls -y
    - git clone https://github.com/bangden07/VPN-Proxy-Installer.git vpn-proxy
    - cd vpn-proxy
    - sudo chmod +x install.sh

script:
    - ./install.sh
after_success: coveralls